version: 1.0.{build}
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
before_build:
- cmd: .\.nuget\nuget restore
build:
  verbosity: minimal
test_script:
- cmd: >-
    cd SmtpServerCore.Test

    dotnet test

